### ISSUE TITLE
Package gym-mujoco

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/gym-feedstock#7]
The original [PR](https://github.com/conda-forge/staged-recipes/pull/11162) where @oblute & I added the recipe does not go into much detail about why gym-mujoco was not packages, except referencing https://github.com/openai/mujoco-py#install-mujoco. This was perhaps from a casual reading, because as @vnlitvinov brought up [here](https://github.com/conda-forge/gym-feedstock/pull/6#discussion_r535919196):

> @vnlitvinov: also @h-vetinari are you sure mujoco license is forbidding? I've checked out their github, and it seems that it should be possible to install mujoco-py as it's MIT-licensed (which in turn would not work without MuJoCo, which is a paid thing, but that's a separate issue).

My response: 
> @h-vetinari: That's a good point. I looked at the original staged-recipes PR, but couldn't find more rationale, except from (perhaps casual) reading of https://github.com/openai/mujoco-py#install-mujoco. But you're right, according to https://github.com/openai/mujoco-py/blob/master/LICENSE.md, we should be able to package it.
> 
> Double-checking this one with @oblute @scopatz

Opening a separate issue since it's unrelated to #6

**Comment by vnlitvinov** [comment]
Some more food for thought - according to https://github.com/openai/mujoco-py#install-and-use-mujoco-py, `mujoco-py` would probably **not** work without MuJoCo installed (which in turn requires special license).

Thus I'm not sure it's really worth the hassle. However, it can be considered worth packaging proprietary MuJoCo binaries as conda package, too (they won't work unless license is provided, but that is one step less to do for the end user anyway).

**Comment by traversaro** [comment]
Exactly, Google DeepMind acquired it and open sourced it, see https://www.deepmind.com/blog/open-sourcing-mujoco .
